name: Sync to DO Spaces

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*'
      env:
        AWS_S3_BUCKET: tdn
        AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET }}
        DEST_DIR: 'assets/'
        AWS_S3_ENDPOINT: https://sfo2.digitaloceanspaces.com